"""Utility helpers for visualising simulation rollouts."""

from __future__ import annotations

import math
from typing import Any, Dict, Iterable, List, Optional

import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.axes import Axes
from matplotlib.figure import Figure

import torch

from src.core.simulators import SimulationResult
from src.core.systems import System

__all__ = ["SimulationRenderer"]


class SimulationRenderer:
    """Render one or more :class:`SimulationResult` objects."""

    def __init__(self, system: System, dt: float, nt: int) -> None:
        self.system = system
        self.dt = float(dt)
        self.nt = int(nt)

        self.fig: Figure
        self.ax: Axes
        self.fig, self.ax = plt.subplots()

        self._trajectories: List[Dict[str, Any]] = []
        self._animation: Optional[FuncAnimation] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def add(self, simulation_result: SimulationResult) -> None:
        """Register ``simulation_result`` for inclusion in the animation."""

        if simulation_result.system is not self.system:
            raise ValueError('SimulationResult was generated by a different system instance.')

        entry: Dict[str, Any] = {'result': simulation_result, 'artists': None}
        self._trajectories.append(entry)

        # Allow the system to perform any setup and create per-trajectory artists.
        initial_index = 0
        entry['artists'] = self._invoke_system(entry, initial_index)

        # Any change to the set of trajectories invalidates the current animation.
        self._animation = None

    def show(self) -> None:
        """Display the interactive animation window."""

        self._ensure_animation()
        plt.show()

    def save(self, filepath: str, fps: Optional[int] = None) -> None:
        """Persist the animation to ``filepath`` using Matplotlib writers."""

        self._ensure_animation()

        save_kwargs = {}
        if fps is not None:
            save_kwargs['fps'] = fps
        self._animation.save(filepath, **save_kwargs)

    def save_frames(self, directory: str, fmt: str = 'png') -> None:
        """Save each frame as an image file in ``directory``.

        This renders the animation frames sequentially and writes figure snapshots
        named frame_0000.png, frame_0001.png, ... into the target directory.
        """
        import os
        os.makedirs(directory, exist_ok=True)
        # Initialize artists
        self._init_animation()
        n = self._num_frames()
        for i in range(n):
            self._update(i)
            filepath = os.path.join(directory, f"frame_{i:04d}.{fmt}")
            self.fig.savefig(filepath, bbox_inches='tight')

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _ensure_animation(self) -> None:
        if self._animation is not None:
            return
        if not self._trajectories:
            raise RuntimeError('No simulation has been added – call add() first.')

        self._animation = FuncAnimation(
            self.fig,
            self._update,
            init_func=self._init_animation,
            frames=self._num_frames(),
            interval=max(int(math.ceil(self.dt * 1000.0)), 1),
            blit=False,
        )

    def _num_frames(self) -> int:
        lengths = [self._trajectory_length(entry['result']) for entry in self._trajectories]
        return max(lengths)

    def _trajectory_length(self, result: SimulationResult) -> int:
        states = result.states
        return states.shape[-2]

    def _init_animation(self) -> Iterable[object]:
        artists: List[object] = []
        for entry in self._trajectories:
            updated = self._invoke_system(entry, frame=0)
            entry['artists'] = updated
            artists.extend(self._collect_artists(updated))
        return artists

    def _update(self, frame: int) -> Iterable[object]:
        artists: List[object] = []
        for entry in self._trajectories:
            length = self._trajectory_length(entry['result'])
            current_frame = min(frame, length - 1)
            updated = self._invoke_system(entry, frame=current_frame)
            entry['artists'] = updated
            artists.extend(self._collect_artists(updated))
        return artists

    def _invoke_system(self, entry: Dict[str, Any], frame: int) -> Any:
        result: SimulationResult = entry['result']

        state = self._slice_at(result.states, frame)
        control = self._slice_at(result.controls, min(frame, max(result.controls.shape[-2] - 1, 0)))
        disturbance = self._slice_at(
            result.disturbances,
            min(frame, max(result.disturbances.shape[-2] - 1, 0)),
        )
        uncertainty = self._slice_at(
            result.uncertainties,
            min(frame, max(result.uncertainties.shape[-2] - 1, 0)),
        )
        time_value = float(result.times[min(frame, result.times.shape[0] - 1)].item())
        history = self._trajectory_history(result, frame)

        return self.system.render(
            state=state,
            control=control,
            disturbance=disturbance,
            uncertainty=uncertainty,
            time=time_value,
            ax=self.ax,
            artists=entry.get('artists'),
            history=history,
            frame=frame,
        )

    def _trajectory_history(self, result: SimulationResult, frame: int) -> Optional[torch.Tensor | Dict[str, torch.Tensor]]:
        states = result.states
        if states.numel() == 0:
            return None
        # Collapse batch dimension if present
        if states.ndim == 3:
            states = states[0]
        actual_hist = states[: frame + 1]
        # If estimated states are available, include them as a separate history
        est = getattr(result, 'estimated_states', None)
        if est is not None and isinstance(est, torch.Tensor) and est.numel() > 0:
            if est.ndim == 3:
                est = est[0]
            est_hist = est[: frame + 1]
            return {'actual': actual_hist, 'estimated': est_hist}
        return actual_hist

    def _slice_at(self, tensor: torch.Tensor, index: int) -> Optional[torch.Tensor]:
        if tensor.numel() == 0:
            return None
        if tensor.ndim == 3:
            index = max(min(index, tensor.shape[1] - 1), 0)
            return tensor[0, index]
        index = max(min(index, tensor.shape[0] - 1), 0)
        return tensor[index]

    def _collect_artists(self, artists: Any) -> List[object]:
        if artists is None:
            return []
        if isinstance(artists, dict):
            collected: List[object] = []
            for value in artists.values():
                collected.extend(self._collect_artists(value))
            return collected
        if isinstance(artists, (list, tuple)):
            collected: List[object] = []
            for value in artists:
                collected.extend(self._collect_artists(value))
            return collected
        return [artists]